name: NuGet Push

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v4     
        with:
            dotnet-version: '8.0.x'  

      - name: Build and Publish
        run: |  
          cd ./src/RedisRateLimiting/
          dotnet pack -c Release -o artifacts -p:PackageVersion=1.0.0 -p:PackageId=Gorillapower.RedisRateLimiting

      - name: Push
        run: dotnet nuget push ./src/RedisRateLimiting/artifacts/Gorillapower.RedisRateLimiting.1.0.0.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json
